### PR TITLE
fixes https://github.com/digital-me/phplist-plugin-ldap/issues/3

### PR DESCRIPTION
**Pull request by tfnab**

### CODE REVIEW

**Comment by michield** [comment]
@btlogy are you still maintaining this plugin, or shall we move it into the phpList organisation?

**Comment by btlogy** [comment]
I did fix this issue a while ago in an internal repo...
Which means I was not really maintaining this one very well indeed.

**Comment by btlogy** [comment]
> @btlogy are you still maintaining this plugin, or shall we move it into the phpList organisation?

So, yes @michield, I'll be glad to move it into phpList organisation: how to proceed?

**Comment by tfnab** [comment]
> I did fix this issue a while ago in an internal repo...

Are there any other changes in that repo that you might want to share with the community/public?

**Comment by btlogy** [comment]
Good you ask. I've just check: there is no other difference.
BTW, I guess this change makes the plugin not backward compatible with older version of PHPList, right?

**Comment by tfnab** [comment]
I would think so. The change that triggered the bug (https://github.com/phpList/phplist3/commit/a3a442ba9ed187fe46eeb070239b8ec200d033da) was committed to phpList in January 2017, i.e. almost two years ago. Not sure when it was merged into a "stable" version, but the plugin has been incompatible for quite some time.

On compatibility in general: the $ldap_except_users relies on code duplicated from on older version of phpList. So it's likely to a) break again in the future, b) contain bugs that have been fixed in the meantime, c) malfunction under certain circumstances. I have not dived into the code and I am reluctant to just duplicate code from a newer version. I would like to find out whether there is a possibility to call the method from phpList rather than using duplicated code... unfortunately this is a side-project and I may not have the resources to follow up on this

**Comment by michield** [comment]
> > @btlogy are you still maintaining this plugin, or shall we move it into the phpList organisation?
> 
> So, yes @michield, I'll be glad to move it into phpList organisation: how to proceed?

tbh, @btlogy considering the speed of your reply and handling this, we can leave it here for now. But if you ever decide to abandon it, we can work something out :-)

**Pull request merged**
